[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "https://fortress-modeler-backend-pqiu2rcyqq-km.a.run.app"
  VITE_GOOGLE_CLIENT_ID = "928130924917-fcu6m854ua2ajutk3eu191okl4f29uqv.apps.googleusercontent.com"
  VITE_SUPABASE_URL = "https://jjearfzmvmpohbebcnju.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqZWFyZnptdm1wb2hiZWJjbmp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxOTY1NzksImV4cCI6MjA2Nzc3MjU3OX0.GVpM2scX6hCJYgrvMv2v6kJERnwiZ-it51Fqt4xJ400"
  VITE_USE_SUPABASE_BACKEND = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200