[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "https://fortress-modeler-backend-pqiu2rcyqq-km.a.run.app"
  VITE_GOOGLE_CLIENT_ID = "928130924917-fcu6m854ua2ajutk3eu191okl4f29uqv.apps.googleusercontent.com"
  VITE_SUPABASE_URL = "https://vplafscpcsxdxbyoxfhq.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwbGFmc2NwY3N4ZHhkeGJ5b3hmaHEiLCJyb2xlIjoiYW5vbiIsImlhdCI6MTc1MTI2NjkwNCwiZXhwIjoyMDY2ODQyOTA0fQ.y3RL3Aq-2q_OW0AKoawV0-Q0JFpleTs5xHt52lVAsnQ"
  VITE_USE_SUPABASE_BACKEND = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200